// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace _0_InventáriodeEquipamentosdeRede.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    [Migration("20260917122854_CriarBanco")]
    partial class CriarBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Arquivo", b =>
                {
                    b.Property<int>("UltimoRegistro")
                        .HasColumnType("INTEGER");

                    b.ToTable("arquivo");
                });
#pragma warning restore 612, 618
        }
    }
}
